name: Essential features

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  save_output:
    name: Save output
    runs-on: ubuntu-latest

    steps:
      - shell: bash
        run: expr 1 * 1 > mult.log

      - name: Save output
        uses: actions/upload-artifact@v4
        with:
          name: mul-log-file
          path: mul.log

  # print_output:
  #   name: Print output
  #   runs-on: ubuntu-latest
  #   needs: save_output

  #   steps:
  #     - name: Download a single artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: sum-log-file
