name: Essential features

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Save output
    runs-on: ubuntu-latest

    steps:
      - shell: bash
        run: echo "Hello, world!" > output.log

      - name: Save output
        uses: actions/upload-artifact@v4
        with:
          name: output-log-file
          path: output.log
